repos:
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.86.0
  #   hooks:
  #     - id: terraform_fmt
  #     #- id: terraform_docs
  #     #- id: terraform_tflint
  #     #- id: terraform_tfsec
  #     #- id: terraform_validate
  #     #- id: terraform_plan
  - repo: local
    hooks:
      - id: avm
        name: AVM Pre-Commit Hook
        entry: bash -c '[[ "$OSTYPE" == "msys" ]] && ./avm.bat pre-commit || ./avm pre-commit'
        language: system
        types: [terraform]      

